server:
  port: 8081

spring:
  application:
    name: canto-gateway

  # 使用 Nacos 作为服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: canto-user
          uri: lb://canto-user
          predicates:
            - Path=/swagger/**, /api/user/**
          filters:
            - StripPrefix=1

      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

