server:
  port: 8081

spring:
  application:
    name: canto-gateway

  redis:
    host: 47.100.93.25
    port: 6379
    password: aini1314liliqun
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
    #连接超时时间
    timeout: 10000

  # 使用 Nacos 作为服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.93.25:8848

    gateway:
      routes:
        - id: canto-user
          uri: lb://canto-user
          predicates:
            - Path=/swagger/**, /api/user/**
          filters:
            - StripPrefix=1

      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

