# 端口
server:
  port: 8082

spring:
  # 服务名称
  application:
    name: canto-user

  # nacos注册地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAIi0duivWKN6O9
      secret-key: C5Kk2DFBibxucA5Ila0afSRsK0Xqtw

  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/canto?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: aini1314liliqun

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.vmall.entity
  mapper-locations: classpath:/xml/*Mapper.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'

